### ISSUE TITLE
Lab Report 1 Feedback 

### ISSUE THREAD

**Issue by mrkylesmith** [ygchavez/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- Good, and nice helpful screenshots here also. 
- [] All relevant code examples written with backticks (```)
- You need to have all code examples or commands written with backticks like this:
- ```ls -l```
- ```cat <file```
- etc.  Make sure you do this ^ throughout the report. 
- [x] All screenshots correspond to the described steps
- [] All titles of sections are formatted as headers or similar
- You should provide headers for each section so each part is easier to find/read.
- [x] Lab report is on its own page, not the index page
- [] Last example counts keystrokes and shows how to run remotely saving time
- You need to complete this part (step 7 from lab 1) 
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Good start, but it seems that you still have a few sections to finish.  Please reference the lab 1 report at the end of lab 2. Please feel free to integrate any of my suggestions if you would like. 

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by ygchavez** [comment]
Hello, I just wanted to make sure that I correctly made changes to the saving time and counting keystrokes portion of this lab report. Thank you!

**Comment by mrkylesmith** [comment]
Yes, this looks great!  And I see you added section headers and backticks for all your commands.  Great job, looks good!
